DO $$
BEGIN
  ALTER TYPE "CpcProcedureType" ADD VALUE IF NOT EXISTS 'BOLETIM_OCORRENCIA';
  ALTER TYPE "CpcProcedureType" ADD VALUE IF NOT EXISTS 'INQUERITO_CIVIL';
  ALTER TYPE "CpcProcedureType" ADD VALUE IF NOT EXISTS 'NAO_HOUVE';
  ALTER TYPE "CpcProcedureType" ADD VALUE IF NOT EXISTS 'INQUERITO_POLICIAL_COMUM';
  ALTER TYPE "CpcProcedureType" ADD VALUE IF NOT EXISTS 'NOTICIA_FATO';
  ALTER TYPE "CpcProcedureType" ADD VALUE IF NOT EXISTS 'CONSELHO_DISCIPLINA';
  ALTER TYPE "CpcProcedureType" ADD VALUE IF NOT EXISTS 'CONSELHO_JUSTIFICACAO';
END $$;
