export const qk = {
  me: ["auth","me"] as const,
  tasks: (filters: Record<string, any>) => ["tasks", filters] as const,
  taskAssignees: (localityId: string) => ["taskAssignees", localityId] as const,
  taskComments: (taskId: string) => ["taskComments", taskId] as const,
  activityComments: (activityId: string) => ["activityComments", activityId] as const,
  activities: (filters: Record<string, any>) => ["activities", filters] as const,
  task: (id: string) => ["task", id] as const,
  gantt: (filters: Record<string, any>) => ["gantt", filters] as const,
  calendarYear: (year: number, filters: Record<string, any>) => ["calendar", year, filters] as const,
  localityProgress: (id: string) => ["localityProgress", id] as const,
  dashboardNational: (filters: Record<string, any>) => ["dashboardNational", filters] as const,
  dashboardRecruits: ["dashboardRecruits"] as const,
  roles: ["rbac","roles"] as const,
  permissions: ["rbac","permissions"] as const,
  taskTemplates: ["taskTemplates"] as const,
  notices: (filters: Record<string, any>) => ["notices", filters] as const,
  meetings: (filters: Record<string, any>) => ["meetings", filters] as const,
  checklists: (filters: Record<string, any>) => ["checklists", filters] as const,
  elos: (filters: Record<string, any>) => ["elos", filters] as const,
  orgChart: (filters: Record<string, any>) => ["orgChart", filters] as const,
  auditLogs: (filters: Record<string, any>) => ["auditLogs", filters] as const,
  localities: ["localities"] as const,
  specialties: ["specialties"] as const,
  eloRoles: ["eloRoles"] as const,
  postos: ["postos"] as const,
  search: (q: string) => ["search", q] as const,
  executiveDashboard: (filters: Record<string, any>) => ["dashboardExecutive", filters] as const,
  kpiDashboard: (filters: Record<string, any>) => ["kpiDashboard", filters] as const,
};
