-- Carga inicial do catálogo de OMs FAB informado pelo comando.
-- "code" e "name" iniciam iguais e podem ser editados na tela administrativa.
WITH om_catalog(code, name) AS (
VALUES
  ('1 CJM', '1 CJM'),
  ('1 EIA', '1 EIA'),
  ('1 ETA', '1 ETA'),
  ('1 GAVCA', '1 GAVCA'),
  ('1 GCC', '1 GCC'),
  ('1 GDA', '1 GDA'),
  ('1 GDAAE', '1 GDAAE'),
  ('1 GTT', '1 GTT'),
  ('1/1 GCC', '1/1 GCC'),
  ('1/1 GT', '1/1 GT'),
  ('1/10 GAV', '1/10 GAV'),
  ('1/11 GAV', '1/11 GAV'),
  ('1/12 GAV', '1/12 GAV'),
  ('1/14 GAV', '1/14 GAV'),
  ('1/15 GAV', '1/15 GAV'),
  ('1/2 GT', '1/2 GT'),
  ('1/3 GAV', '1/3 GAV'),
  ('1/5 GAV', '1/5 GAV'),
  ('1/7 GAV', '1/7 GAV'),
  ('1/8 GAV', '1/8 GAV'),
  ('1/9 GAV', '1/9 GAV'),
  ('10 CJM', '10 CJM'),
  ('10 RM', '10 RM'),
  ('11 CJM', '11 CJM'),
  ('12 CJM', '12 CJM'),
  ('2 CJM', '2 CJM'),
  ('2 EIA', '2 EIA'),
  ('2 ETA', '2 ETA'),
  ('2 GDAAE', '2 GDAAE'),
  ('2/1 GCC', '2/1 GCC'),
  ('2/10 GAV', '2/10 GAV'),
  ('2/2 GT', '2/2 GT'),
  ('2/3 GAV', '2/3 GAV'),
  ('2/5 GAV', '2/5 GAV'),
  ('2/6 GAV', '2/6 GAV'),
  ('2/7 GAV', '2/7 GAV'),
  ('2/8 GAV', '2/8 GAV'),
  ('2BTLINFFUZNAV', '2BTLINFFUZNAV'),
  ('2ESQDASAU HFASP', '2ESQDASAU HFASP'),
  ('3 CJM', '3 CJM'),
  ('3 ETA', '3 ETA'),
  ('3 GDAAE', '3 GDAAE'),
  ('3/1 GCC', '3/1 GCC'),
  ('3/10 GAV', '3/10 GAV'),
  ('3/3 GAV', '3/3 GAV'),
  ('3/7 GAV', '3/7 GAV'),
  ('3/8 GAV', '3/8 GAV'),
  ('3RM-SMR', '3RM-SMR'),
  ('4 CJM', '4 CJM'),
  ('4 RM', '4 RM'),
  ('4/1 GCC', '4/1 GCC'),
  ('5 CJM', '5 CJM'),
  ('5 ETA', '5 ETA'),
  ('5 RM', '5 RM'),
  ('5/1 GCC', '5/1 GCC'),
  ('5/8 GAV', '5/8 GAV'),
  ('6 CJM', '6 CJM'),
  ('6 ETA', '6 ETA'),
  ('6 RM', '6 RM'),
  ('7 CJM', '7 CJM'),
  ('7 ETA', '7 ETA'),
  ('7/8 GAV', '7/8 GAV'),
  ('8 CJM', '8 CJM'),
  ('8 RM', '8 RM'),
  ('9 CJM', '9 CJM'),
  ('AD AFR SUL', 'AD AFR SUL'),
  ('AD ALEMANH', 'AD ALEMANH'),
  ('AD ARGENT', 'AD ARGENT'),
  ('AD BOLIVIA', 'AD BOLIVIA'),
  ('AD CHILE', 'AD CHILE'),
  ('AD CHINA', 'AD CHINA'),
  ('AD COLOMB', 'AD COLOMB'),
  ('AD EEUU', 'AD EEUU'),
  ('AD EQUADOR', 'AD EQUADOR'),
  ('AD FRANCA', 'AD FRANCA'),
  ('AD INGL', 'AD INGL'),
  ('AD ISRAEL', 'AD ISRAEL'),
  ('AD ITALIA', 'AD ITALIA'),
  ('AD PARAG', 'AD PARAG'),
  ('AD PERU', 'AD PERU'),
  ('AD PORT', 'AD PORT'),
  ('AD URUGUAI', 'AD URUGUAI'),
  ('AD VENEZ', 'AD VENEZ'),
  ('ADDEFNAVEXAEREAU', 'ADDEFNAVEXAEREAU'),
  ('ADDEFNAVEXAERETIOPIA', 'ADDEFNAVEXAERETIOPIA'),
  ('ADEXAEAL', 'ADEXAEAL'),
  ('ADEXAEPR', 'ADEXAEPR'),
  ('ADIAER', 'ADIAER'),
  ('ADIDEFEXAERTCHECA', 'ADIDEFEXAERTCHECA'),
  ('ADIDEFNAVEXAERINDIA', 'ADIDEFNAVEXAERINDIA'),
  ('ADIDEFNAVEXAERINTAVI', 'ADIDEFNAVEXAERINTAVI'),
  ('ADIDEFNAVEXAERLIBANO', 'ADIDEFNAVEXAERLIBANO'),
  ('ADIDEFNAVEXAERSEBETG', 'ADIDEFNAVEXAERSEBETG'),
  ('ADIDEFNAVEXAERSUECIA', 'ADIDEFNAVEXAERSUECIA'),
  ('ADIDEFNEAINDIA', 'ADIDEFNEAINDIA'),
  ('ADIDEFTUR', 'ADIDEFTUR'),
  ('ADIFA', 'ADIFA'),
  ('ADIFA CHIN', 'ADIFA CHIN'),
  ('ADIFA COLO', 'ADIFA COLO'),
  ('ADIFA ESP', 'ADIFA ESP'),
  ('ADIFA IRAN', 'ADIFA IRAN'),
  ('ADIFA ISRA', 'ADIFA ISRA'),
  ('ADIFA IUGO', 'ADIFA IUGO'),
  ('ADIFA MEXI', 'ADIFA MEXI'),
  ('ADIFA RUSS', 'ADIFA RUSS'),
  ('AFA', 'AFA'),
  ('AGAFA', 'AGAFA'),
  ('AGU', 'AGU'),
  ('AMVPR', 'AMVPR'),
  ('ANAC', 'ANAC'),
  ('ASOCEA', 'ASOCEA'),
  ('ASPAER', 'ASPAER'),
  ('BAAF', 'BAAF'),
  ('BAAN', 'BAAN'),
  ('BABE', 'BABE'),
  ('BABR', 'BABR'),
  ('BABV', 'BABV'),
  ('BACG', 'BACG'),
  ('BACO', 'BACO'),
  ('BAFL', 'BAFL'),
  ('BAFZ', 'BAFZ'),
  ('BAGL', 'BAGL'),
  ('BAMN', 'BAMN'),
  ('BANT', 'BANT'),
  ('BAPV', 'BAPV'),
  ('BASC', 'BASC'),
  ('BASM', 'BASM'),
  ('BASP', 'BASP'),
  ('BAST', 'BAST'),
  ('BASV', 'BASV'),
  ('BREVET', 'BREVET'),
  ('BREVET-VET', 'BREVET-VET'),
  ('CABE', 'CABE'),
  ('CABW', 'CABW'),
  ('CAE', 'CAE'),
  ('CASLODE', 'CASLODE'),
  ('CBNB', 'CBNB'),
  ('CCA BR', 'CCA BR'),
  ('CCA RJ', 'CCA RJ'),
  ('CCA SJ', 'CCA SJ'),
  ('CCAFA', 'CCAFA'),
  ('CCISE', 'CCISE'),
  ('CDA', 'CDA'),
  ('CDCAER', 'CDCAER'),
  ('CDCIBER', 'CDCIBER'),
  ('CEAP', 'CEAP'),
  ('CECAFA MD', 'CECAFA MD'),
  ('CECAT', 'CECAT'),
  ('CECOMSAER', 'CECOMSAER'),
  ('CELOG', 'CELOG'),
  ('CEMAL', 'CEMAL'),
  ('CEMCOHA', 'CEMCOHA'),
  ('CENCIAR', 'CENCIAR'),
  ('CENDOC', 'CENDOC'),
  ('CENIPA', 'CENIPA'),
  ('CENSIPAM CR-BE', 'CENSIPAM CR-BE'),
  ('CENSIPAM CR-BR', 'CENSIPAM CR-BR'),
  ('CENSIPAM CR-MN', 'CENSIPAM CR-MN'),
  ('CENSIPAM CR-PV', 'CENSIPAM CR-PV'),
  ('CEPE', 'CEPE'),
  ('CFIAE', 'CFIAE'),
  ('CFIAE-BR', 'CFIAE-BR'),
  ('CFIAE-LS', 'CFIAE-LS'),
  ('CGABEG', 'CGABEG'),
  ('CGNA', 'CGNA'),
  ('CIAAR', 'CIAAR'),
  ('CIAER', 'CIAER'),
  ('CIAER AGINT-MA', 'CIAER AGINT-MA'),
  ('CIAER AGINT-SP', 'CIAER AGINT-SP'),
  ('CID/JID', 'CID/JID'),
  ('CIGE', 'CIGE'),
  ('CIMAER', 'CIMAER'),
  ('CINDACTA I', 'CINDACTA I'),
  ('CINDACTA II', 'CINDACTA II'),
  ('CINDACTA III', 'CINDACTA III'),
  ('CINDACTA IV', 'CINDACTA IV'),
  ('CISCEA', 'CISCEA'),
  ('CLA', 'CLA'),
  ('CLBI', 'CLBI'),
  ('CMA BOL', 'CMA BOL'),
  ('CMB', 'CMB'),
  ('CMBEL', 'CMBEL'),
  ('CMBH', 'CMBH'),
  ('CMC', 'CMC'),
  ('CMCG', 'CMCG'),
  ('CMF', 'CMF'),
  ('CMJF', 'CMJF'),
  ('CMM', 'CMM'),
  ('CMPA', 'CMPA'),
  ('CMR', 'CMR'),
  ('CMRJ', 'CMRJ'),
  ('CMS', 'CMS'),
  ('CMSM', 'CMSM'),
  ('CMSP', 'CMSP'),
  ('CMVM', 'CMVM'),
  ('CO-AN', 'CO-AN'),
  ('CO-FZ', 'CO-FZ'),
  ('CO-NT', 'CO-NT'),
  ('COJAER', 'COJAER'),
  ('COMAE', 'COMAE'),
  ('COMAER', 'COMAER'),
  ('COMARA', 'COMARA'),
  ('COMDCIBER', 'COMDCIBER'),
  ('COMESQDAP-1', 'COMESQDAP-1'),
  ('COMEXER', 'COMEXER'),
  ('COMF CISCE', 'COMF CISCE'),
  ('COMF MMR', 'COMF MMR'),
  ('COMF SIVAM', 'COMF SIVAM'),
  ('COMFIREM/C-130H', 'COMFIREM/C-130H'),
  ('COMGAP', 'COMGAP'),
  ('COMGAP AAL_SJ', 'COMGAP AAL_SJ'),
  ('COMGEP', 'COMGEP'),
  ('COMPREP', 'COMPREP'),
  ('COMREC-EMBRAER', 'COMREC-EMBRAER'),
  ('COPAC', 'COPAC'),
  ('COPE-P', 'COPE-P'),
  ('COPE-S', 'COPE-S'),
  ('CPBV', 'CPBV'),
  ('CPORAER SJ', 'CPORAER SJ'),
  ('CRCEA-SE', 'CRCEA-SE'),
  ('CSPFA-BE', 'CSPFA-BE'),
  ('CSPFA-FZ', 'CSPFA-FZ'),
  ('CTLA', 'CTLA'),
  ('CTRB', 'CTRB'),
  ('DACO MN', 'DACO MN'),
  ('DACO OW', 'DACO OW'),
  ('DACO TT', 'DACO TT'),
  ('DACO UA', 'DACO UA'),
  ('DCTA', 'DCTA'),
  ('DECEA', 'DECEA'),
  ('DGP_EB', 'DGP_EB'),
  ('DIRAD', 'DIRAD'),
  ('DIRAP', 'DIRAP'),
  ('DIREF', 'DIREF'),
  ('DIRENS', 'DIRENS'),
  ('DIRINFRA', 'DIRINFRA'),
  ('DIRMAB', 'DIRMAB'),
  ('DIRSA', 'DIRSA'),
  ('DSTAEEI', 'DSTAEEI'),
  ('DSTAEUA', 'DSTAEUA'),
  ('DSTAEVH', 'DSTAEVH'),
  ('DTCEA-AA', 'DTCEA-AA'),
  ('DTCEA-AF', 'DTCEA-AF'),
  ('DTCEA-AN', 'DTCEA-AN'),
  ('DTCEA-AR', 'DTCEA-AR'),
  ('DTCEA-BE', 'DTCEA-BE'),
  ('DTCEA-BQ', 'DTCEA-BQ'),
  ('DTCEA-BR', 'DTCEA-BR'),
  ('DTCEA-BV', 'DTCEA-BV'),
  ('DTCEA-BW', 'DTCEA-BW'),
  ('DTCEA-CF', 'DTCEA-CF'),
  ('DTCEA-CG', 'DTCEA-CG'),
  ('DTCEA-CGU', 'DTCEA-CGU'),
  ('DTCEA-CO', 'DTCEA-CO'),
  ('DTCEA-CR', 'DTCEA-CR'),
  ('DTCEA-CT', 'DTCEA-CT'),
  ('DTCEA-CTD', 'DTCEA-CTD'),
  ('DTCEA-CY', 'DTCEA-CY'),
  ('DTCEA-CZ', 'DTCEA-CZ'),
  ('DTCEA-EG', 'DTCEA-EG'),
  ('DTCEA-EP', 'DTCEA-EP'),
  ('DTCEA-FA', 'DTCEA-FA'),
  ('DTCEA-FI', 'DTCEA-FI'),
  ('DTCEA-FL', 'DTCEA-FL'),
  ('DTCEA-FN', 'DTCEA-FN'),
  ('DTCEA-FZ', 'DTCEA-FZ'),
  ('DTCEA-GA', 'DTCEA-GA'),
  ('DTCEA-GI', 'DTCEA-GI'),
  ('DTCEA-GL', 'DTCEA-GL'),
  ('DTCEA-GM', 'DTCEA-GM'),
  ('DTCEA-GW', 'DTCEA-GW'),
  ('DTCEA-IZ', 'DTCEA-IZ'),
  ('DTCEA-LP', 'DTCEA-LP'),
  ('DTCEA-LS', 'DTCEA-LS'),
  ('DTCEA-MDI', 'DTCEA-MDI'),
  ('DTCEA-MN', 'DTCEA-MN'),
  ('DTCEA-MO', 'DTCEA-MO'),
  ('DTCEA-MQ', 'DTCEA-MQ'),
  ('DTCEA-MT', 'DTCEA-MT'),
  ('DTCEA-NT', 'DTCEA-NT'),
  ('DTCEA-PCO', 'DTCEA-PCO'),
  ('DTCEA-PL', 'DTCEA-PL'),
  ('DTCEA-PS', 'DTCEA-PS'),
  ('DTCEA-PV', 'DTCEA-PV'),
  ('DTCEA-RB', 'DTCEA-RB'),
  ('DTCEA-SC', 'DTCEA-SC'),
  ('DTCEA-SI', 'DTCEA-SI'),
  ('DTCEA-SJ', 'DTCEA-SJ'),
  ('DTCEA-SL', 'DTCEA-SL'),
  ('DTCEA-SM', 'DTCEA-SM'),
  ('DTCEA-SN', 'DTCEA-SN'),
  ('DTCEA-SRO', 'DTCEA-SRO'),
  ('DTCEA-ST', 'DTCEA-ST'),
  ('DTCEA-STA', 'DTCEA-STA'),
  ('DTCEA-STI', 'DTCEA-STI'),
  ('DTCEA-SV', 'DTCEA-SV'),
  ('DTCEA-TF', 'DTCEA-TF'),
  ('DTCEA-TNB', 'DTCEA-TNB'),
  ('DTCEA-TRM', 'DTCEA-TRM'),
  ('DTCEA-TT', 'DTCEA-TT'),
  ('DTCEA-UA', 'DTCEA-UA'),
  ('DTCEA-UG', 'DTCEA-UG'),
  ('DTCEA-VH', 'DTCEA-VH'),
  ('DTCEA-YS', 'DTCEA-YS'),
  ('DTCEATM-RJ', 'DTCEATM-RJ'),
  ('DTI', 'DTI'),
  ('DTS', 'DTS'),
  ('EAOAR', 'EAOAR'),
  ('EAS', 'EAS'),
  ('ECE', 'ECE'),
  ('ECEMAR', 'ECEMAR'),
  ('ECEME', 'ECEME'),
  ('ECP-GPX', 'ECP-GPX'),
  ('ECP-IJA', 'ECP-IJA'),
  ('ECP-POA', 'ECP-POA'),
  ('ECP-SSA', 'ECP-SSA'),
  ('EDA', 'EDA'),
  ('EEAR', 'EEAR'),
  ('EGN', 'EGN'),
  ('EMAER', 'EMAER'),
  ('EMAPA', 'EMAPA'),
  ('ENADCIBER', 'ENADCIBER'),
  ('EPCAR', 'EPCAR'),
  ('ESCESP EXER', 'ESCESP EXER'),
  ('ESD', 'ESD'),
  ('ESEFEX', 'ESEFEX'),
  ('ESG', 'ESG'),
  ('FAYS', 'FAYS'),
  ('GABAER', 'GABAER'),
  ('GAC-AFS', 'GAC-AFS'),
  ('GAC-CASA', 'GAC-CASA'),
  ('GAC-EUROCOPTER', 'GAC-EUROCOPTER'),
  ('GAC-INFRA AN', 'GAC-INFRA AN'),
  ('GAC-PAC', 'GAC-PAC'),
  ('GAC-SAAB', 'GAC-SAAB'),
  ('GALC', 'GALC'),
  ('GAP AF', 'GAP AF'),
  ('GAP BE', 'GAP BE'),
  ('GAP BQ', 'GAP BQ'),
  ('GAP BR', 'GAP BR'),
  ('GAP BV', 'GAP BV'),
  ('GAP CO', 'GAP CO'),
  ('GAP DF', 'GAP DF'),
  ('GAP FZ', 'GAP FZ'),
  ('GAP GL', 'GAP GL'),
  ('GAP LS', 'GAP LS'),
  ('GAP MN', 'GAP MN'),
  ('GAP PV', 'GAP PV'),
  ('GAP RF', 'GAP RF'),
  ('GAP RJ', 'GAP RJ'),
  ('GAP SJ', 'GAP SJ'),
  ('GAP SP', 'GAP SP'),
  ('GECAMP', 'GECAMP'),
  ('GEIV', 'GEIV'),
  ('GITE', 'GITE'),
  ('GLOG-AF', 'GLOG-AF'),
  ('GLOG-AN', 'GLOG-AN'),
  ('GLOG-BE', 'GLOG-BE'),
  ('GLOG-BR', 'GLOG-BR'),
  ('GLOG-BV', 'GLOG-BV'),
  ('GLOG-CG', 'GLOG-CG'),
  ('GLOG-CO', 'GLOG-CO'),
  ('GLOG-GL', 'GLOG-GL'),
  ('GLOG-MN', 'GLOG-MN'),
  ('GLOG-NT', 'GLOG-NT'),
  ('GLOG-PV', 'GLOG-PV'),
  ('GLOG-SC', 'GLOG-SC'),
  ('GLOG-SM', 'GLOG-SM'),
  ('GLOG-YS', 'GLOG-YS'),
  ('GOP-AF', 'GOP-AF'),
  ('GOP-AN', 'GOP-AN'),
  ('GOP-BE', 'GOP-BE'),
  ('GOP-BR', 'GOP-BR'),
  ('GOP-BV', 'GOP-BV'),
  ('GOP-CG', 'GOP-CG'),
  ('GOP-CO', 'GOP-CO'),
  ('GOP-GL', 'GOP-GL'),
  ('GOP-MN', 'GOP-MN'),
  ('GOP-NT', 'GOP-NT'),
  ('GOP-PV', 'GOP-PV'),
  ('GOP-SC', 'GOP-SC'),
  ('GOP-SM', 'GOP-SM'),
  ('GSAU-AK', 'GSAU-AK'),
  ('GSAU-AN', 'GSAU-AN'),
  ('GSAU-BQ', 'GSAU-BQ'),
  ('GSAU-BV', 'GSAU-BV'),
  ('GSAU-CG', 'GSAU-CG'),
  ('GSAU-CT', 'GSAU-CT'),
  ('GSAU-FL', 'GSAU-FL'),
  ('GSAU-FZ', 'GSAU-FZ'),
  ('GSAU-GR', 'GSAU-GR'),
  ('GSAU-GW', 'GSAU-GW'),
  ('GSAU-LS', 'GSAU-LS'),
  ('GSAU-PV', 'GSAU-PV'),
  ('GSAU-SC', 'GSAU-SC'),
  ('GSAU-SJ', 'GSAU-SJ'),
  ('GSAU-SM', 'GSAU-SM'),
  ('GSAU-SV', 'GSAU-SV'),
  ('GSAU-YS', 'GSAU-YS'),
  ('GSD-AF', 'GSD-AF'),
  ('GSD-AK', 'GSD-AK'),
  ('GSD-AN', 'GSD-AN'),
  ('GSD-BE', 'GSD-BE'),
  ('GSD-BQ', 'GSD-BQ'),
  ('GSD-BR', 'GSD-BR'),
  ('GSD-BV', 'GSD-BV'),
  ('GSD-CC', 'GSD-CC'),
  ('GSD-CG', 'GSD-CG'),
  ('GSD-CO', 'GSD-CO'),
  ('GSD-CT', 'GSD-CT'),
  ('GSD-FL', 'GSD-FL'),
  ('GSD-FZ', 'GSD-FZ'),
  ('GSD-GL', 'GSD-GL'),
  ('GSD-GW', 'GSD-GW'),
  ('GSD-LS', 'GSD-LS'),
  ('GSD-MN', 'GSD-MN'),
  ('GSD-MT', 'GSD-MT'),
  ('GSD-NT', 'GSD-NT'),
  ('GSD-PV', 'GSD-PV'),
  ('GSD-RF', 'GSD-RF'),
  ('GSD-RJ', 'GSD-RJ'),
  ('GSD-SC', 'GSD-SC'),
  ('GSD-SJ', 'GSD-SJ'),
  ('GSD-SM', 'GSD-SM'),
  ('GSD-SP', 'GSD-SP'),
  ('GSD-ST', 'GSD-ST'),
  ('GSD-SV', 'GSD-SV'),
  ('GSD-YS', 'GSD-YS'),
  ('GSI ER-AR', 'GSI ER-AR'),
  ('GSI ER-CA', 'GSI ER-CA'),
  ('GSI ER-RJO', 'GSI ER-RJO'),
  ('GSI ER-SP', 'GSI ER-SP'),
  ('GSIPR', 'GSIPR'),
  ('GTE', 'GTE'),
  ('HAAF', 'HAAF'),
  ('HABE', 'HABE'),
  ('HACO', 'HACO'),
  ('HAMN', 'HAMN'),
  ('HARF', 'HARF'),
  ('HCA', 'HCA'),
  ('HFA', 'HFA'),
  ('HFAB', 'HFAB'),
  ('HFAG', 'HFAG'),
  ('HFASP', 'HFASP'),
  ('HMILACG', 'HMILACG'),
  ('I COMAR', 'I COMAR'),
  ('IAE', 'IAE'),
  ('IAOP', 'IAOP'),
  ('ICA', 'ICA'),
  ('ICEA', 'ICEA'),
  ('IEAD', 'IEAD'),
  ('IEAV', 'IEAV'),
  ('IEFA', 'IEFA'),
  ('IEFA-SJ', 'IEFA-SJ'),
  ('IFI', 'IFI'),
  ('II COMAR', 'II COMAR'),
  ('III COMAR', 'III COMAR'),
  ('ILA', 'ILA'),
  ('IMAE', 'IMAE'),
  ('INCAER', 'INCAER'),
  ('INCAER-DF', 'INCAER-DF'),
  ('IPA', 'IPA'),
  ('IPEV', 'IPEV'),
  ('ITA', 'ITA'),
  ('IV COMAR', 'IV COMAR'),
  ('JJAER', 'JJAER'),
  ('LAQFA', 'LAQFA'),
  ('MDEFESA', 'MDEFESA'),
  ('MISSAO BR-MESMA LOC', 'MISSAO BR-MESMA LOC'),
  ('MISSAO BR-OUTRA LOC', 'MISSAO BR-OUTRA LOC'),
  ('MISSAO EXT', 'MISSAO EXT'),
  ('MTAB', 'MTAB'),
  ('MTAB-BOLIVIA', 'MTAB-BOLIVIA'),
  ('MUSAL', 'MUSAL'),
  ('NUHANT', 'NUHANT'),
  ('NUITA-FZ', 'NUITA-FZ'),
  ('OABR', 'OABR'),
  ('OACI', 'OACI'),
  ('OARF', 'OARF'),
  ('OASD', 'OASD'),
  ('ONU', 'ONU'),
  ('ORGEXT', 'ORGEXT'),
  ('OSFAB', 'OSFAB'),
  ('PAAF', 'PAAF'),
  ('PAAN', 'PAAN'),
  ('PABE', 'PABE'),
  ('PABR', 'PABR'),
  ('PACO', 'PACO'),
  ('PACT', 'PACT'),
  ('PAGL', 'PAGL'),
  ('PAGW', 'PAGW'),
  ('PALS', 'PALS'),
  ('PAMA GL', 'PAMA GL'),
  ('PAMA LS', 'PAMA LS'),
  ('PAMA SP', 'PAMA SP'),
  ('PAMB RJ', 'PAMB RJ'),
  ('PAME RJ', 'PAME RJ'),
  ('PAMN', 'PAMN'),
  ('PANT', 'PANT'),
  ('PAPASP-ST', 'PAPASP-ST'),
  ('PARF', 'PARF'),
  ('PASJ', 'PASJ'),
  ('PASP', 'PASP'),
  ('PAYS', 'PAYS'),
  ('PECIM-AF', 'PECIM-AF'),
  ('PECIM-AK', 'PECIM-AK'),
  ('PECIM-AN', 'PECIM-AN'),
  ('PECIM-BE', 'PECIM-BE'),
  ('PECIM-BQ', 'PECIM-BQ'),
  ('PECIM-BV', 'PECIM-BV'),
  ('PECIM-CG', 'PECIM-CG'),
  ('PECIM-CO', 'PECIM-CO'),
  ('PECIM-CT', 'PECIM-CT'),
  ('PECIM-DF', 'PECIM-DF'),
  ('PECIM-FL', 'PECIM-FL'),
  ('PECIM-FZ', 'PECIM-FZ'),
  ('PECIM-GW', 'PECIM-GW'),
  ('PECIM-LS', 'PECIM-LS'),
  ('PECIM-MN', 'PECIM-MN'),
  ('PECIM-NT', 'PECIM-NT'),
  ('PECIM-PV', 'PECIM-PV'),
  ('PECIM-RF', 'PECIM-RF'),
  ('PECIM-SJ', 'PECIM-SJ'),
  ('PECIM-SM', 'PECIM-SM'),
  ('PECIM-SP', 'PECIM-SP'),
  ('PECIM-ST', 'PECIM-ST'),
  ('PECIM-SV', 'PECIM-SV'),
  ('PECIM-YS', 'PECIM-YS'),
  ('PGJM-DF', 'PGJM-DF'),
  ('PJM-BV', 'PJM-BV'),
  ('PJM-CE', 'PJM-CE'),
  ('PJM-CG', 'PJM-CG'),
  ('PJM-CT', 'PJM-CT'),
  ('PJM-RF', 'PJM-RF'),
  ('PJM-RJ', 'PJM-RJ'),
  ('PJM-SV', 'PJM-SV'),
  ('PRMN/10 RM', 'PRMN/10 RM'),
  ('RBJID', 'RBJID'),
  ('RECABI', 'RECABI'),
  ('SAGAB', 'SAGAB'),
  ('SASDAB-DIRAD', 'SASDAB-DIRAD'),
  ('SECPROM', 'SECPROM'),
  ('SEFA', 'SEFA'),
  ('SEREP-BE', 'SEREP-BE'),
  ('SEREP-BR', 'SEREP-BR'),
  ('SEREP-CO', 'SEREP-CO'),
  ('SEREP-MN', 'SEREP-MN'),
  ('SEREP-RF', 'SEREP-RF'),
  ('SEREP-RJ', 'SEREP-RJ'),
  ('SEREP-SP', 'SEREP-SP'),
  ('SERINFRA-BE', 'SERINFRA-BE'),
  ('SERINFRA-BR', 'SERINFRA-BR'),
  ('SERINFRA-CO', 'SERINFRA-CO'),
  ('SERINFRA-MN', 'SERINFRA-MN'),
  ('SERINFRA-NT', 'SERINFRA-NT'),
  ('SERINFRA-RJ', 'SERINFRA-RJ'),
  ('SERINFRA-SJ', 'SERINFRA-SJ'),
  ('SERIPA I', 'SERIPA I'),
  ('SERIPA II', 'SERIPA II'),
  ('SERIPA III', 'SERIPA III'),
  ('SERIPA IV', 'SERIPA IV'),
  ('SERIPA V', 'SERIPA V'),
  ('SERIPA VI', 'SERIPA VI'),
  ('SERIPA VII', 'SERIPA VII'),
  ('UNIFA', 'UNIFA'),
  ('V COMAR', 'V COMAR'),
  ('VI COMAR', 'VI COMAR'),
  ('VII COMAR', 'VII COMAR')
)
INSERT INTO "Locality" (
  "id",
  "code",
  "name",
  "createdAt",
  "updatedAt"
)
SELECT
  concat('loc_', gen_random_uuid()::text),
  om.code,
  om.name,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
FROM om_catalog om
ON CONFLICT ("code") DO NOTHING;
