export function createDefaultCertificateLayout() {
  return {
    backgroundColor: "#F8F4EC",
    frameColor: "#8E642A",
    elements: [
      {
        id: "watermark-fab",
        type: "image",
        label: "Marca d'água FAB",
        src: "/mockups/certificate/fab.png",
        xPct: 0.37,
        yPct: 0.31,
        widthPct: 0.28,
        zIndex: 1,
        visible: true,
        opacity: 0.08,
      },
      {
        id: "logo-comgep",
        type: "image",
        label: "Logo COMGEP",
        src: "/mockups/certificate/comgep.png",
        xPct: 0.105,
        yPct: 0.12,
        widthPct: 0.085,
        zIndex: 8,
        visible: true,
        opacity: 1,
      },
      {
        id: "logo-fab",
        type: "image",
        label: "Logo FAB",
        src: "/mockups/certificate/fab.png",
        xPct: 0.79,
        yPct: 0.115,
        widthPct: 0.125,
        zIndex: 8,
        visible: true,
        opacity: 1,
      },
      {
        id: "institution",
        type: "text",
        label: "Órgão",
        text: "COMANDO-GERAL DO PESSOAL",
        xPct: 0.355,
        yPct: 0.115,
        widthPct: 0.29,
        zIndex: 9,
        visible: true,
        opacity: 1,
        fontFamily: '"Sora", "Manrope", sans-serif',
        fontSizePx: 13,
        fontWeight: 800,
        fontStyle: "normal",
        colorHex: "#4E5960",
        textAlign: "center",
        lineHeight: 1.1,
      },
      {
        id: "title",
        type: "text",
        label: "Título",
        text: "CERTIFICADO",
        xPct: 0.295,
        yPct: 0.15,
        widthPct: 0.41,
        zIndex: 10,
        visible: true,
        opacity: 1,
        fontFamily: 'Georgia, "Times New Roman", serif',
        fontSizePx: 46,
        fontWeight: 500,
        fontStyle: "normal",
        colorHex: "#111111",
        textAlign: "center",
        lineHeight: 0.96,
      },
      {
        id: "body-intro",
        type: "text",
        label: "Texto antes do nome",
        text: "Certifico que",
        xPct: 0.18,
        yPct: 0.365,
        widthPct: 0.64,
        zIndex: 10,
        visible: true,
        opacity: 1,
        fontFamily: '"Sora", "Manrope", sans-serif',
        fontSizePx: 25,
        fontWeight: 400,
        fontStyle: "normal",
        colorHex: "#111111",
        textAlign: "center",
        lineHeight: 1.28,
      },
      {
        id: "recipient-name",
        type: "variable",
        label: "Nome completo do lote",
        text: "NOME COMPLETO DO PARTICIPANTE",
        variableKey: "recipient_full_name",
        xPct: 0.18,
        yPct: 0.425,
        widthPct: 0.64,
        zIndex: 11,
        visible: true,
        opacity: 1,
        fontFamily: '"Sora", "Manrope", sans-serif',
        fontSizePx: 27,
        fontWeight: 700,
        fontStyle: "normal",
        colorHex: "#111111",
        textAlign: "center",
        lineHeight: 1.18,
      },
      {
        id: "body-details",
        type: "text",
        label: "Texto depois do nome",
        text: "ministrou, no COMGEP, a palestra com o tema Assédio Sexual na FAB.",
        xPct: 0.18,
        yPct: 0.505,
        widthPct: 0.64,
        zIndex: 10,
        visible: true,
        opacity: 1,
        fontFamily: '"Sora", "Manrope", sans-serif',
        fontSizePx: 24,
        fontWeight: 400,
        fontStyle: "normal",
        colorHex: "#111111",
        textAlign: "center",
        lineHeight: 1.28,
      },
      {
        id: "signature",
        type: "image",
        label: "Assinatura",
        src: "/mockups/certificate/assinatura.png",
        xPct: 0.423,
        yPct: 0.698,
        widthPct: 0.21,
        zIndex: 12,
        visible: true,
        opacity: 1,
        mixBlendMode: "multiply",
      },
      {
        id: "signature-line",
        type: "line",
        label: "Linha da assinatura",
        xPct: 0.335,
        yPct: 0.802,
        widthPct: 0.34,
        zIndex: 11,
        visible: true,
        opacity: 1,
        colorHex: "#111111",
        thicknessPx: 2,
      },
      {
        id: "signer-name",
        type: "text",
        label: "Nome do assinante",
        text: "Regilânio Isaías Aguiar de Melo Cel Av",
        xPct: 0.335,
        yPct: 0.823,
        widthPct: 0.34,
        zIndex: 10,
        visible: true,
        opacity: 1,
        fontFamily: '"Sora", "Manrope", sans-serif',
        fontSizePx: 16,
        fontWeight: 800,
        fontStyle: "normal",
        colorHex: "#111111",
        textAlign: "center",
        lineHeight: 1.12,
      },
      {
        id: "signer-role",
        type: "text",
        label: "Cargo do assinante",
        text: "Comandante do CINDacta II",
        xPct: 0.335,
        yPct: 0.852,
        widthPct: 0.34,
        zIndex: 10,
        visible: true,
        opacity: 1,
        fontFamily: '"Sora", "Manrope", sans-serif',
        fontSizePx: 14,
        fontWeight: 600,
        fontStyle: "normal",
        colorHex: "#4E5960",
        textAlign: "center",
        lineHeight: 1.12,
      },
      {
        id: "date",
        type: "text",
        label: "Data",
        text: "Brasília, 19 de junho de 2026.",
        xPct: 0.68,
        yPct: 0.782,
        widthPct: 0.24,
        zIndex: 10,
        visible: true,
        opacity: 1,
        fontFamily: '"Sora", "Manrope", sans-serif',
        fontSizePx: 16,
        fontWeight: 500,
        fontStyle: "normal",
        colorHex: "#111111",
        textAlign: "right",
        lineHeight: 1.2,
      },
    ],
  };
}
